name: Build

on:
  push:
    branches:
      - main
      - main-*
      - develop
      - release/*
      - feature/*
      - ci/*
    tags:
      - v*
  pull_request:

concurrency:
  group: rust-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18
          - 20
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }} with yarn caching
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build
