name: Lint

on:
  push:
    branches:
      - main
      - main-*
      - develop
      - release/*
      - feature/*
      - ci/*
    tags:
      - v*
  pull_request:

env:
  CI: 1
  CARGO_TERM_COLOR: always
  NIGHTLY_TOOLCHAIN: nightly-2023-02-20
  NODE_VERSION: 16

jobs:
  format:
    name: Lint format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
          override: true
          default: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install nixpkgs-fmt
        run: |
          if ! command -v nixpkgs-fmt &> /dev/null
          then
            cargo +stable install nixpkgs-fmt
          fi

      - name: Run nixpkgs-fmt
        run: |
          nixpkgs-fmt --check .

      - name: Run prettier
        uses: creyD/prettier_action@v4.3
        with:
          dry: true
          prettier_options: --check **/*.{js,ts,md,json,yaml}

  commit:
    name: Lint commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run commitlint
        uses: wagoid/commitlint-github-action@v5.3.1
        with:
          firstParent: false

  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: codespell-project/codespell-problem-matcher@v1

      - name: Codespell
        uses: codespell-project/actions-codespell@master

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js ${{ env.NODE_VERSION }} with yarn caching
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Setup yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run eslint
        run: yarn lint
