name: Publish to NPM

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  NODE_VERSION: 18

jobs:
  publish-npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org
          cache: yarn

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Publish Packages
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          YARN_NPM_REGISTRY_SERVER: https://registry.npmjs.org
          YARN_NPM_ALWAYS_AUTH: 'true'
        run: |
          yarn workspaces foreach --worktree --no-private --topological -v \
            npm publish --access public --tolerate-republish
